ccflags-y += -I$(srctree)/drivers/misc/mediatek/gyroscope/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hwmon/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/accelerometer/lsm6ds0

obj-y	:=  lsm6ds0.o

